# Site settings
title: Fellipe Brito
header-img: img/home-bg.jpg
email: email@fellipebrito.com
description: "Christ follower, Husband, Nerd, Surfer, Entrepreneur and Software Writer"
baseurl: ""
url: "http://fellipebrito.com"
twitter_username: fellipeeduardo
github_username:  fellipebrito
linkedin_username:  fellipebrito

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
