# Site settings
title: Fellipe Brito
header-img: img/home-bg.jpg
email: email@fellipebrito.com
description: "Christ follower, Husband, Nerd, Surfer, Entrepreneur and Software Writer"
baseurl: ""
url: "http://fellipebrito.com/"
twitter_username: fellipeeduardo
github_username:  fellipebrito
linkedin_username:  fellipebrito

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 20
paginate_path:  "index/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Multiple languages
gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

languages:          ['en', 'pt']

# If not config, the first of languages will be the default
language_default:   'en'
